# How to build? (version is docker container related, not mbuild version)
# docker build . -f Dockerfile-min  -t cmelab/mbuild:0.1.0

# How to run?
# docker run --rm -itp 8888:8888 cmelab/mbuild:0.1.0 jupyter notebook --notebook-dir=/home/ --ip='*' --port=8888 --no-browser --allow-root

FROM mmh42/docker-alpine-miniconda3

RUN conda install notebook -c conda-forge -y
RUN pip install ipywidgets==7.0.0b0
RUN jupyter nbextension enable --py --sys-prefix widgetsnbextension

RUN pip install numpy==1.13.1
RUN pip install pytraj==2.0.2
RUN pip install matplotlib==2.0.2
RUN pip install moviepy==0.2.2.11
RUN pip install imageio==1.6
RUN pip install pillow==4.2.1
RUN pip install nglview==1.0.a0
RUN nglview install
RUN nglview enable
RUN conda install -c cmelab -c mosdef -c bioconda mbuild -c glotzer -c omnia -y

CMD jupyter notebook --ip=* --port=8888 --no-browser --notebook-dir=/opt/app/data --allow-root --NotebookApp.iopub_data_rate_limit=100000000
